'use strict';
const $ = id => document.getElementById(id);
let session, templateId = null, hasTemplate = false, busy = false, step = 1, activeItem = null, currentViewFile = null, currentDocument = null, currentWorksheetId = null;
const items = [];
function el(tag, text, cls) { const n=document.createElement(tag); if(text!==undefined)n.textContent=text; if(cls)n.className=cls; return n; }
function button(text, action, cls) { const n=el('button',text,cls); n.type='button'; n.addEventListener('click',action); return n; }
function notice(text,error=false) { $('notice').textContent=text; $('notice').className=error?'error':''; }
async function api(path,data,raw=false) {
  const options={headers:{'X-Gdcalc-Token':session.token}};
  if(data!==undefined){options.method='POST';options.headers['Content-Type']=raw?'application/octet-stream':'application/json';options.body=raw?data:JSON.stringify(data);}
  const r=await fetch(path,options);const value=await r.json();if(!r.ok)throw new Error(value.error||'The server could not complete this request.');return value;
}
async function run(fn) { if(busy)return;busy=true;$('workspace').disabled=true;try{await fn();}catch(e){notice(e.message,true);}finally{busy=false;$('workspace').disabled=false;render();} }
function setStep(value) { step=value;for(let i=1;i<=4;i++)$('step-'+i).hidden=i!==step;document.querySelectorAll('[data-step]').forEach(n=>{n.classList.toggle('active',Number(n.dataset.step)===step);n.classList.toggle('done',Number(n.dataset.step)<step);n.setAttribute('aria-current',Number(n.dataset.step)===step?'step':'false');});render(); }
function overrides() { const values={};for(const line of $('overrides').value.split('\n').map(x=>x.trim()).filter(Boolean)){const m=line.match(/^([A-Za-z][A-Za-z0-9_]*)\s*=\s*(.+)$/);if(!m||!Number.isFinite(Number(m[2]))||Object.hasOwn(values,m[1]))throw new Error('Use one unique VARIABLE=NUMBER override per line.');values[m[1]]=Number(m[2]);}return values; }
function options(item){return {id:item.id,cases:item.selected,load_source:$('basis').value,template_id:templateId,overrides:overrides()};}
function ready(){return items.filter(i=>i.inspection&&i.selected.length&&i.inspection.envelope);}
function invalidate(){for(const item of items)item.preview=null;}
async function refresh(item){item.preview=null;item.error=null;if(!item.selected.length){item.inspection.envelope=null;item.error='Select at least one load case.';return;}try{item.inspection=await api('/api/inspect',{id:item.id,cases:item.selected,load_source:$('basis').value});}catch(e){item.error=e.message;item.inspection.envelope=null;}}
async function download(file){const r=await fetch('/api/download/'+file.id,{headers:{'X-Gdcalc-Token':session.token}});if(!r.ok)throw new Error((await r.json()).error);const url=URL.createObjectURL(await r.blob());const a=el('a');a.href=url;a.download=file.name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
function head(item,label){const h=el('div',undefined,'card-head'),title=el('div');title.append(el('h3',item.name));if(item.relativePath&&item.relativePath!==item.name)title.append(el('p',item.relativePath,'card-path'));title.append(el('span',label,'tag'));h.append(title);return h;}
function diffView(value,all=false,envelope=null){const fragment=el('div');const changed=value.changes.filter(c=>c.kind!=='added');const added=value.changes.filter(c=>c.kind==='added');const h=el('div',undefined,'diff-header');h.append(el('span','ORIGINAL TEMPLATE'),el('span','GENERATED WORKSHEET'));fragment.append(h);for(const c of (all?value.changes:changed)){const row=el('div',undefined,'diff-row');row.append(el('pre',c.before||'— New native expression','diff-before'),el('pre',(c.after||'— Removed')+(envelope&&({P_a:'P',V_u:'Vy',M_uy:'My',M_uz:'Mz'})[c.variable]?'\nReport preview: '+envelope[({P_a:'P',V_u:'Vy',M_uy:'My',M_uz:'Mz'})[c.variable]]+(c.variable.startsWith('M')?' kip-in':' kip'):''),'diff-after'));fragment.append(row);}fragment.append(el('p',`${changed.length} changed expressions · ${added.length} new native input/envelope expressions`,'diff-summary'));if(!all&&added.length){const details=el('details');details.append(el('summary',`See ${added.length} added expressions`));for(const c of added)details.append(el('pre',c.after,'source-text'));fragment.append(details);}return fragment;}
function validation(parent,value,calculation=null){const status=el('div',undefined,'result-status');status.append(el('span','✓ Package structure checked'),el('span',calculation?.calculated?'✓ Calculated with CalcpadCE':'Mathcad execution unverified','pending'));parent.append(status,el('p',`${value.math_regions} math regions · ${value.cached_results} cached results · ${value.package_parts} package parts`,'validation-stats'));}
function render(){
  $('file-count').textContent=items.length+' FILE'+(items.length===1?'':'S');$('count').textContent=items.length;
  $('queue-summary').textContent=ready().length+' ready for comparison';
  $('review-next').disabled=!items.length;$('compare-next').disabled=!hasTemplate||!ready().length;
  $('convert-all').disabled=!items.some(i=>i.preview&&!i.result);
  $('inspect-template').disabled=!hasTemplate;$('inspect-template-review').disabled=!hasTemplate;
  const imports=$('import-list');imports.replaceChildren();
  for(const item of items){const row=el('div',undefined,'import-row');row.append(el('span',item.kind==='report'?'REPORT':'MCDX'),el('b',item.name),el('span',item.error?'Needs attention':'Imported','tag'+(item.error?' error':'')),button('×',()=>{items.splice(items.indexOf(item),1);render();},'quiet'));imports.append(row);}
  const queue=$('queue');queue.replaceChildren();if(!items.length)queue.append(el('div','Import files to review their contents.','empty'));
  for(const item of items){const card=el('article',undefined,'card');card.append(head(item,item.inspection?'Inputs detected':item.error?'Needs attention':'Worksheet'));
    if(item.inspection){card.append(el('p','Select load cases · STR selected automatically','case-caption'));const cases=el('div',undefined,'cases');for(const c of item.inspection.cases){const label=el('label',undefined,'case-label'),input=el('input');input.type='checkbox';input.checked=item.selected.includes(c.id);input.addEventListener('change',()=>run(async()=>{item.selected=input.checked?[...item.selected,c.id].sort((a,b)=>a-b):item.selected.filter(id=>id!==c.id);await refresh(item);}));label.append(input,document.createTextNode(`${c.id} · ${c.name||'Unnamed'}`));cases.append(label);}card.append(cases);
      if(item.inspection.envelope){const values=el('div',undefined,'envelope');for(const [key,value]of Object.entries(item.inspection.envelope)){const cell=el('div',undefined,'measure');cell.append(el('span',key),el('strong',Number(value.toPrecision(6)).toString()),el('small',key.startsWith('M')?'kip-in':'kip'));values.append(cell);}card.append(values);}
    }
    if(item.error)card.append(el('p',item.error,'error-text'));
    if(item.validation)validation(card,item.validation);
    if(item.id){const actions=el('div',undefined,'card-actions');actions.append(button(item.kind==='report'?'Open original report ↗':'Open worksheet ↗',()=>run(()=>inspect(item.id))));if(item.validation)actions.append(button('Validate again',()=>run(async()=>{item.validation=await api('/api/validate',{id:item.id});notice('Package checks passed. Native execution requires Mathcad.');})));card.append(actions);}queue.append(card);
  }
  const comparisons=$('comparisons');comparisons.replaceChildren();let count=0;
  for(const item of items){if(!item.preview&&!item.previewError)continue;count++;const card=el('article',undefined,'card');card.append(head(item,item.preview?'Ready to generate':'Needs attention'));if(item.preview){card.append(diffView(item.preview.diff,false,item.preview.envelope));const actions=el('div',undefined,'card-actions');actions.append(button('Inspect proposed worksheet ↗',()=>run(()=>inspect(item.preview.worksheet.id))));card.append(actions);}else card.append(el('p',item.previewError,'error-text'));comparisons.append(card);}if(!count)comparisons.append(el('div','Review your loads, then choose Compare changes to preview the worksheet.','empty'));
  const results=$('results');results.replaceChildren();for(const item of items.filter(i=>i.previewError)){const failed=el('article',undefined,'card');failed.append(head(item,'Generation needs attention'),el('p',item.previewError,'error-text'));results.append(failed);}for(const item of items.filter(i=>i.result))results.append(resultCard(item.result,item.name));if(!items.some(i=>i.result))results.append(el('div','Generated worksheets will appear here. Previous files are under Saved worksheets.','empty'));
}
function resultCard(result,name){const card=el('article',undefined,'card');card.append(head({name},'Generated'));if(result.validation)validation(card,result.validation,result.calculation);card.append(el('p',result.output,'path'));const actions=el('div',undefined,'card-actions');actions.append(button('Open worksheet ↗',()=>run(()=>inspect(result.worksheet.id)),'primary-button'),button('See diff',()=>run(()=>inspectDiff(result.worksheet.id))),button('Download .mcdx',()=>run(()=>download(result.worksheet))),button('Download audit',()=>run(()=>download(result.audit))),button('Validate output',()=>run(async()=>{result.validation=await api('/api/validate',{id:result.worksheet.id});notice('Output package checks passed. Native calculation requires Mathcad.');})));if(result.open_worksheet)actions.append(button('Download .cpd',()=>run(()=>download(result.open_worksheet))),button('Download calculated page',()=>run(()=>download(result.calculated_worksheet))));card.append(actions);return card;}
function dialog(title,type,note){$('inspector-title').textContent=title;$('inspector-type').textContent=type;$('inspector-note').textContent=note;$('inspector-content').replaceChildren();currentDocument=null;$('inspector-search').value='';$('inspector-search').hidden=false;document.body.classList.add('document-open');if(!$('inspector').open)$('inspector').show();}
async function inspect(id,mode='file'){currentViewFile=id;currentDocument=null;const found=items.find(i=>i.id===id||i.preview?.worksheet.id===id||i.result?.worksheet.id===id);if(found)activeItem=found;const data=await api('/api/view',{id});if(data.kind!=='report')currentWorksheetId=id;dialog(data.name,data.kind==='report'?'ORIGINAL SOURCE':'WORKSHEET INSPECTOR',data.kind==='report'?'Original report text. Search or scroll to inspect the source.':'Text and native equations extracted from the .mcdx. This is not a native Mathcad page rendering; no expressions are executed.');const body=$('inspector-content');$('view-calculation').disabled=!data.calculated_html;if(data.calculated_html&&mode==='calculated'){$('inspector-title').textContent=data.name.replace(/\.mcdx$/i,'.cpd');$('inspector-type').textContent='CALCULATED WORKSHEET';$('inspector-note').textContent='Calculated locally with CalcpadCE. This page is a result snapshot; the .cpd and .mcdx files contain the formulas. Prime execution remains unverified.';body.append(button('Inspect native Mathcad expressions',()=>run(()=>inspect(id,'file'))));const calculated=el('div',undefined,'calculated');appendCalculated(calculated,data.calculated_html);body.append(calculated);return;}if(data.kind==='report'){const lines=data.text.split('\n');for(let n=0;n<lines.length;n+=100){const block=el('pre',lines.slice(n,n+100).map((line,i)=>String(n+i+1).padStart(5)+'  '+line).join('\n'),'source-text');block.dataset.search=block.textContent.toLowerCase();body.append(block);}}else{renderDocument(data,body);return;}}
async function inspectDiff(id){const data=await api('/api/diff',{id});dialog('Original → generated','EXPRESSION DIFF',data.scope);$('inspector-search').hidden=true;$('inspector-content').append(diffView(data));}
async function history(){const data=await api('/api/history');dialog('Saved worksheets','OUTPUT HISTORY','Completed conversions on this server. Outputs and source snapshots survive server restarts.');$('inspector-search').hidden=true;for(const result of data)$('inspector-content').append(resultCard(result,result.worksheet.name));if(!data.length)$('inspector-content').append(el('div','No saved worksheets yet.','empty'));}
async function importFiles(files){let added=0,failed=0,skipped=0;for(const file of files){const ext=file.name.split('.').pop().toLowerCase();if(!['gp11t','txt','mcdx'].includes(ext)){skipped++;continue;}if(items.length>=100)throw new Error('The queue is limited to 100 files. Start a new session for more.');const item={name:file.name,relativePath:file.webkitRelativePath,kind:ext==='mcdx'?'worksheet':'report'};notice('Reading '+file.name+'…');try{if(file.size>(item.kind==='report'?16:32)*1024*1024)throw new Error('File exceeds the upload size limit.');Object.assign(item,await api('/api/upload?'+new URLSearchParams({name:file.name,kind:item.kind}),file,true));if(item.inspection){item.selected=item.inspection.selected_cases;item.error=item.inspection.selection_required;if($('basis').value!=='effects'&&item.selected.length)await refresh(item);}added++;}catch(e){item.error=e.message;failed++;}items.push(item);activeItem=item;render();}if(activeItem?.id)await inspect(activeItem.id);notice(`${added} imported · ${failed} failed · ${skipped} unsupported files skipped.`,failed>0);}
for(const id of ['files','folder']){$('choose-'+(id==='files'?'files':'folder')).addEventListener('click',()=>$(id).click());$(id).addEventListener('change',e=>{const files=Array.from(e.target.files);e.target.value='';run(()=>importFiles(files));});}
$('choose-template').addEventListener('click',()=>$('template').click());
$('template').addEventListener('change',e=>{const file=e.target.files[0];e.target.value='';if(!file)return;run(async()=>{if(file.size>32*1024*1024)throw new Error('Template exceeds 32 MiB.');const value=await api('/api/upload?'+new URLSearchParams({name:file.name,kind:'template'}),file,true);templateId=value.id;hasTemplate=true;invalidate();$('template-name').textContent=value.name;$('template-status').textContent='Package checked · inspect the inherited assumptions';notice('Template selected. Review its inherited design assumptions.');});});
for(const id of ['inspect-template','inspect-template-review'])$(id).addEventListener('click',()=>run(()=>inspect(templateId||'default-template')));
$('basis').addEventListener('change',()=>run(async()=>{for(const item of items.filter(i=>i.inspection))await refresh(item);notice('Local load source updated. Review the refreshed envelopes.');}));
$('overrides').addEventListener('input',()=>{invalidate();render();});
$('review-next').addEventListener('click',()=>setStep(2));
$('compare-next').addEventListener('click',()=>run(async()=>{setStep(3);for(const item of ready()){notice('Preparing changes for '+item.name+'…');item.previewError=null;try{item.preview=await api('/api/preview',options(item));item.result=null;}catch(e){item.preview=null;item.previewError=e.message;}render();}const prepared=items.find(i=>i.preview);if(prepared){activeItem=prepared;await inspectDiff(prepared.preview.worksheet.id);}notice('Review the diff, then generate the ready worksheets.');}));
$('convert-all').addEventListener('click',()=>run(async()=>{const pending=items.filter(i=>i.preview&&!i.result);let done=0;for(const item of pending){notice('Generating '+item.name+'…');try{item.result=await api('/api/convert',options(item));done++;}catch(e){item.previewError=e.message;notice(e.message,true);}render();}setStep(4);const generated=items.find(i=>i.result);if(generated){activeItem=generated;await inspect(generated.result.worksheet.id);}notice(`${done} worksheets generated · ${pending.length-done} failed. Open a worksheet to inspect it.`,done<pending.length);}));
for(const n of document.querySelectorAll('[data-step]'))n.addEventListener('click',()=>setStep(Number(n.dataset.step)));
for(const n of document.querySelectorAll('[data-back]'))n.addEventListener('click',()=>setStep(Number(n.dataset.back)));
for(const id of ['open-history','refresh-history'])$(id).addEventListener('click',()=>{if(session)run(history);});
$('close-inspector').addEventListener('click',()=>{$('inspector').close();document.body.classList.remove('document-open');});
$('inspector-search').addEventListener('input',()=>{const query=$('inspector-search').value.toLowerCase();if(currentDocument){currentDocument.search(query);return;}const body=$('inspector-content');const rows=body.querySelector('.calculated')?.children||body.children;for(const row of rows)row.hidden=Boolean(query)&&!(row.dataset.search||row.textContent.toLowerCase()).includes(query);});
for(const name of ['dragenter','dragover'])$('dropzone').addEventListener(name,e=>{e.preventDefault();if(!busy)$('dropzone').classList.add('dragging');});
for(const name of ['dragleave','drop'])$('dropzone').addEventListener(name,e=>{e.preventDefault();$('dropzone').classList.remove('dragging');});
$('dropzone').addEventListener('drop',e=>{if(busy)return;const entries=Array.from(e.dataTransfer.items||[]).map(i=>i.webkitGetAsEntry?.());if(entries.some(e=>e?.isDirectory)){notice('Use Select folder to include files from a directory.',true);return;}const files=Array.from(e.dataTransfer.files);run(()=>importFiles(files));});
async function connect(){const r=await fetch('/api/session');if(r.status===401){$('login').hidden=false;$('mode').textContent='SERVER WORKSPACE';notice('Sign in to open this workspace.');return;}if(!r.ok)throw new Error('Cannot connect. Use the URL printed by gdcalc serve.');session=await r.json();hasTemplate=Boolean(session.template);$('login').hidden=true;$('template-name').textContent=session.template||'No template selected';$('template-status').textContent=session.template?'Default template · inspect before generating':'Select a compatible .mcdx design template';$('output-dir').textContent=session.output_dir;$('mode').textContent=session.network?'SERVER WORKSPACE':'LOCAL WORKSPACE';$('storage-note').textContent=session.network?'Selected files upload to this server.':'Files stay on this computer.';$('workspace').disabled=false;notice('Engine connected. Import reports and choose a template to begin.');render();if(hasTemplate)await inspect('default-template');}
$('sign-in').addEventListener('click',async()=>{try{const r=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({access_token:$('access-token').value})});$('access-token').value='';if(!r.ok)throw new Error((await r.json()).error);await connect();}catch(e){notice(e.message,true);}});
connect().catch(e=>notice(e.message,true));

function mathNode(value){const allowed=['mrow','mi','mn','mo','mtext','msub','msup','mfrac','msqrt','mroot','mtable','mtr','mtd'];const node=document.createElementNS('http://www.w3.org/1998/Math/MathML',allowed.includes(value.tag)?value.tag:'mtext');if(value.text!==null&&value.text!==undefined)node.textContent=value.text;for(const child of value.children||[])node.append(mathNode(child));return node;}
$('view-template').addEventListener('click',()=>run(()=>inspect(templateId||'default-template')));
$('view-report').addEventListener('click',()=>run(async()=>{if(activeItem?.id)await inspect(activeItem.id);else notice('Import a report first.');}));
$('view-worksheet').addEventListener('click',()=>run(async()=>{const file=activeItem?.result?.worksheet||activeItem?.preview?.worksheet||(currentWorksheetId?{id:currentWorksheetId}:null);if(file)await inspect(file.id);else notice('Compare changes to prepare a worksheet preview.');}));
$('view-diff').addEventListener('click',()=>run(async()=>{const file=activeItem?.result?.worksheet||activeItem?.preview?.worksheet||(currentWorksheetId?{id:currentWorksheetId}:null);if(file)await inspectDiff(file.id);else notice('Compare changes to prepare a diff.');}));

function appendCalculated(parent,html){
  const parsed=new DOMParser().parseFromString(html,'text/html');
  const allowed=new Set(['DIV','P','SPAN','VAR','SUP','SUB','I','B','STRONG','EM','H1','H2','BR']);
  function copy(node){if(node.nodeType===Node.TEXT_NODE)return document.createTextNode(node.textContent);if(node.nodeType!==Node.ELEMENT_NODE||!allowed.has(node.tagName))return document.createTextNode('');const fresh=document.createElement(node.tagName.toLowerCase());if(node.className)fresh.className=node.className;for(const child of node.childNodes)fresh.append(copy(child));return fresh;}
  const wrapper=parsed.body.firstElementChild;for(const node of (wrapper?.tagName==='DIV'?wrapper.childNodes:parsed.body.childNodes))parent.append(copy(node));
}

$('view-calculation').addEventListener('click',()=>run(async()=>{if(currentViewFile)await inspect(currentViewFile,'calculated');}));
function flowNode(value){
  const allowed=['div','p','span','b','i','u','br','ul','li','sub','sup'];const n=el(allowed.includes(value.tag)?value.tag:'span');n.append(document.createTextNode(value.text||''));
  const styles=['color','backgroundColor','fontSize','fontWeight','fontStyle','textDecoration','textAlign','fontFamily'];for(const [key,v] of Object.entries(value.style||{}))if(styles.includes(key))n.style[key]=v;
  for(const child of value.children||[]){n.append(flowNode(child.node));if(child.tail)n.append(document.createTextNode(child.tail));}return n;
}
function renderDocument(data,body){
  $('inspector-type').textContent='FILE VIEW';$('inspector-note').textContent='Layout reconstructed from this .mcdx: stored positions, text, diagrams and equations. '+(data.has_cached_results?'Visible values are saved results in this file, not recalculated.':'This file has no saved results; open Calculation for the separate CalcpadCE results.');
  const page=data.page,toolbar=el('div',undefined,'document-toolbar'),shell=el('div',undefined,'document-shell'),canvas=el('div',undefined,'document-page'),pageSelect=el('select'),label=el('label','Page '),details=el('details',undefined,'document-region-details');
  pageSelect.setAttribute('aria-label','Worksheet page');for(let i=1;i<=page.count;i++){const option=el('option',i+' / '+page.count);option.value=i;pageSelect.append(option);}label.append(pageSelect);
  let number=1,query='';const matches=el('span',undefined,'document-matches');const previous=button('←',()=>show(number-1)),next=button('→',()=>show(number+1)),last=button('Last page',()=>show(page.count));previous.setAttribute('aria-label','Previous page');next.setAttribute('aria-label','Next page');
  toolbar.append(previous,label,next,last,matches);body.append(toolbar,shell,details);shell.append(canvas);
  const detailsTitle=el('summary','Select a region to inspect its source'),detailsBody=el('pre');details.append(detailsTitle,detailsBody);
  function regionNode(r,top,offset){const n=el('div',undefined,'file-region '+r.kind);n.style.left=(page.margins[0]+Number(r.left))+'px';n.style.top=(offset+top)+'px';n.style.width=Number(r.width)+'px';n.style.minHeight=Number(r.height)+'px';for(const [key,v]of Object.entries(r.style||{}))n.style[key]=v;n.dataset.region=r.id;n.title=r.kind==='math'?r.expression:r.text;
    if(r.kind==='math'){const math=document.createElementNS('http://www.w3.org/1998/Math/MathML','math');math.append(mathNode(r.presentation));n.append(math);}else{if(r.image){const img=el('img');img.src=r.image;img.alt='Diagram from worksheet';img.style.width='100%';img.style.height=Number(r.height)+'px';n.append(img);}for(const flow of r.flows||[])n.append(flowNode(flow));if(!r.image&&!(r.flows||[]).length)n.textContent=r.text;}
    if(query&&(r.expression||r.text||'').toLowerCase().includes(query))n.classList.add('search-match');
    n.addEventListener('click',()=>{detailsTitle.textContent='Region '+r.id+' · '+(r.kind==='math'?'Native expression':'File content');detailsBody.textContent=r.xml||r.text;details.open=true;});return n;
  }
  function show(value){number=Math.max(1,Math.min(page.count,Number(value)));pageSelect.value=number;previous.disabled=number===1;next.disabled=number===page.count;canvas.replaceChildren();canvas.style.width=page.width+'px';canvas.style.height=page.height+'px';
    for(const r of data.header)canvas.append(regionNode(r,Number(r.top),12));
    for(const r of data.regions){const top=Number(r.top),p=Math.floor(top/page.content_height)+1;if(p===number)canvas.append(regionNode(r,top-(number-1)*page.content_height,page.margins[1]));}
    for(const r of data.footer)canvas.append(regionNode(r,Number(r.top),page.height-page.margins[3]));
    const pageNumber=el('span',number+' / '+page.count,'file-page-number');canvas.append(pageNumber);resize();
  }
  function resize(){const width=body.clientWidth-32;const scale=Math.max(.25,Math.min(1.25,width/page.width));canvas.style.transform='scale('+scale+')';shell.style.width=(page.width*scale)+'px';shell.style.height=(page.height*scale)+'px';}
  pageSelect.addEventListener('change',()=>show(pageSelect.value));show(1);
  currentDocument={search(text){query=text;const found=data.regions.filter(r=>(r.expression||r.text||'').toLowerCase().includes(text));matches.textContent=text?found.length+' matches':'';if(text&&found.length)show(Math.floor(Number(found[0].top)/page.content_height)+1);else show(number);}};
  const observer=new ResizeObserver(()=>{if(body.contains(shell))resize();else observer.disconnect();});observer.observe(body);
}
